# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33a28bafae5567f7e539234af89c59f923ee558d1e462e35c561643124b7dbc30b0209bb37e994d7d669731116e4ecdf011e7eeaae0f27d8b312b0f1a7eb92d7
  twitter_api_key: dEjneWqkZEiaRnYTScRhKyu6k
  twitter_api_secret: 9X9ujmsVq1bpLCfpDXd0rrfMWWUXA0XG4YMnFgxMpeb8r0JhYI

test:
  secret_key_base: bc95b7397f5b7010e3e0f98049a6aecdab24c88132bfc6b4ea513d65639ec153b1a9c0285ec5d8ccdc30dabbb868ac4a437dc6559b28188883d24e19f0710f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
